"""
Backend package for the Signal TUI Client.

Handles communication with signal-cli (JSON-RPC over HTTP or subprocess),
the SQLite message cache, the temporary download HTTP server, the WAHA
webhook server and the ``Contact`` data model.  No Textual dependency.

This package re-exports the full public (and historical private) API that used
to live in the single ``backend.py`` module, so ``from backend import X`` and
``import backend; backend.X`` keep working unchanged.
"""

from .db import (
    _DB_LOCK,
    CACHE_DIR,
    CACHE_FILE,
    CACHE_RETENTION_DAYS,
    DB_FILE,
    _add_message_to_cache,
    _count_unread,
    _dedup_messages,
    _dedup_messages_by_id,
    _ensure_cache_dir,
    _init_db,
    _load_cache,
    _mark_as_read,
    _migrate_protocol_schema,
    _prune_cache,
    _update_message_id,
    _update_message_status,
    _update_message_status_by_id,
)
from .download import (
    _DOWNLOAD_SERVER,
    _DOWNLOAD_URL_BASE,
    _TEMP_DOWNLOAD_DIR,
    DOWNLOAD_PORT,
    _clean_download_dir,
    _DownloadHTTPHandler,
    _ensure_download_server,
    _get_temp_download_dir,
    _serve_file_path,
    get_local_ip,
    serve_attachment_for_download,
    serve_text_as_file,
)
from .rpc import (
    DAEMON_HTTP_PORT,
    DAEMON_URL,
    PROJECT_DIR,
    SIGNAL_CLI_ATTACHMENTS_DIR,
    SIGNAL_CLI_PATH,
    SSE_URL,
    USER_NUMBER,
    Contact,
    SignalRPCClient,
    _find_signal_cli,
    _get_user_number,
    _is_daemon_running,
    _process_receipt,
    _process_typing,
    _require_user_number,
    _run_subprocess,
    _send_subprocess,
    find_signal_cli,
    get_attachment_path,
)
from .webhook import (
    _WEBHOOK_SERVER,
    WEBHOOK_PORT,
    _WebhookHTTPHandler,
    ensure_webhook_server,
)

__all__ = [
    "CACHE_DIR",
    "CACHE_FILE",
    "CACHE_RETENTION_DAYS",
    "DAEMON_HTTP_PORT",
    "DAEMON_URL",
    "DB_FILE",
    "DOWNLOAD_PORT",
    "PROJECT_DIR",
    "SIGNAL_CLI_ATTACHMENTS_DIR",
    "SIGNAL_CLI_PATH",
    "SSE_URL",
    "USER_NUMBER",
    "WEBHOOK_PORT",
    "_DB_LOCK",
    "_DOWNLOAD_SERVER",
    "_DOWNLOAD_URL_BASE",
    "_TEMP_DOWNLOAD_DIR",
    "_WEBHOOK_SERVER",
    "Contact",
    "SignalRPCClient",
    "_DownloadHTTPHandler",
    "_WebhookHTTPHandler",
    "_add_message_to_cache",
    "_clean_download_dir",
    "_count_unread",
    "_dedup_messages",
    "_dedup_messages_by_id",
    "_ensure_cache_dir",
    "_ensure_download_server",
    "_find_signal_cli",
    "_get_temp_download_dir",
    "_get_user_number",
    "_init_db",
    "_is_daemon_running",
    "_load_cache",
    "_mark_as_read",
    "_migrate_protocol_schema",
    "_process_receipt",
    "_process_typing",
    "_prune_cache",
    "_require_user_number",
    "_run_subprocess",
    "_send_subprocess",
    "_serve_file_path",
    "_update_message_id",
    "_update_message_status",
    "_update_message_status_by_id",
    "ensure_webhook_server",
    "find_signal_cli",
    "get_attachment_path",
    "get_local_ip",
    "serve_attachment_for_download",
    "serve_text_as_file",
]
